Repository tsirysndr/upnp-client-rs, pull requests merged in 2023-04, with the labels that each got.

#7 Fix #1: parser crashes for devices without serviceList
  src/parser.rs
Labels: bug

#9 Attempt to fix #2: Hard parser crashes
  Cargo.toml
  examples/discover.rs
  examples/media_renderer_client.rs
  examples/media_server_client.rs
  src/device_client.rs
  src/discovery.rs
  src/media_renderer.rs
  src/media_server.rs
  src/parser.rs
Labels: bug, enhancement

#10 XMLError to anyhow Error
  Cargo.toml
  README.md
  src/device_client.rs
  src/parser.rs
Labels: enhancement
